### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-infinity_its#1]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by Teresa-CorralesTorresano** [comment]
### MENÚ DEL PROGRAMA
El menú del programa que se adjunta a continuación es el provisional, ya que el válido es el del código final. Presenta dos opciones a elegir: 

- Visualizar las reglas del juego
- Iniciar el juego de la oca

![Menú de inicio código](https://user-images.githubusercontent.com/101127695/170486246-7daf0942-8c24-42fb-ad0e-ca51825f8461.jpg)
![Menú de inicio (negro)](https://user-images.githubusercontent.com/101127695/170486250-56d47514-ce37-44e9-ab06-227adc30eefd.jpg)
