### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-infinity_its#3]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by Teresa-CorralesTorresano** [comment]
### PRINCIPALES FUNCIONES
Las principales funciones de nuestro programa son las siguientes:

- **Banner**: 
Se trata de la cabecera del juego, donde aparece un mensaje inicial junto con un dibujo de dos ocas representando la temática del juego, es decir, una oca clásica.

Se adjunta captura a continuación:
![banner](https://user-images.githubusercontent.com/101127695/170471175-4fd5bf3e-992f-41fb-a4fb-10c280b47be2.jpg)

- **Menú de opciones**:
Función que consta de tres opciones para que elija el usuario. Si elige la primera opción el jugador podrá visualizar las reglas del juego, si elige la segunda se inicia el  juego y si elige la tercera sale del juego.

Captura:
![image](https://user-images.githubusercontent.com/100998828/170671386-d83588ed-a9ba-4335-ad4f-732c46a3261c.png)

- **Tablero**:
Dentro de la función del tablero hemos definido dos tipos, en uno de ellos se muestran las casillas de entrada y salida y el número de casillas que contienen una oca; y el otro tablero te muestra el numero de cada casilla en el orden a seguir (como un gusanito). Además contamos con tres tamaños distintos: pequeño, mediano y grande, para que el usuario tenga posibilidad de elegir.
Captura del tablero mediano como ejemplo:
![Tablero](https://user-images.githubusercontent.com/101127695/170473972-845fa472-5fa5-491c-8e65-360ca459372b.jpg)

- **Dados**:
En esta función hemos creado tres tipos de dados, cada uno de ellos se utilizará dependiendo del tamaño del tablero elegido por el jugador. 
![DADOS](https://user-images.githubusercontent.com/101127695/170474737-04cdadbb-c31c-46f6-ae9f-7318f8ca9989.jpg)
![Dado diminuto](https://user-images.githubusercontent.com/101127695/170481092-72234b68-b990-48d3-a614-48468d96dc8a.jpg)

**Comment by IreneRico** [comment]
- **Pregunta**: 
Por último, hemos añadido la función pregunta, dentro de ellla, se divide en tres partes, cada una para un tema distinto y dentro de las partes, leemos los ficheros de las preguntas y de las respuestas. En esta función comparamos la respuesta dada por el jugador y la respuesta de la pregunta. Si son iguales, el usuario mantiene su posición. Si falla, retrocede tres casillas. 
![Función Preguntas 1](https://user-images.githubusercontent.com/100791927/170546961-36f4947d-e385-4b60-b08d-dd8136f7508d.png)
![Función Preguntas 2](https://user-images.githubusercontent.com/100791927/170546973-e1337353-9b90-4055-a855-4d9d97a7213d.png)
![Función Preguntas 3](https://user-images.githubusercontent.com/100791927/170546988-a2933be6-b886-49aa-92b9-5fd07a4c95f9.png)
