### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-infinity_its#4]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by Teresa-CorralesTorresano** [comment]
### ESTRUCTURAS
En nuestro proyecto se han definido dos estructuras principales (datos tipo _struct_): 

1. **Estructura de los jugadores**:  
La hemos denominado TJugador, y dentro de ella hay un vector en el cual se guardan los nombres (avatares) de los distintos usuarios que participan en el juego, pudiendo ser 1 o 2 jugadores.
2. **Estructura preguntas**
La hemos definido como TRespuestas. El programa está constituido por 24 preguntas de tres temas distintos: literatura y arte, geografía e historia, y entretenimiento (cada uno de ellos tiene 24 preguntas con sus correspondientes respuestas), el usuario debe elegir uno de los temas, y si cae en una casilla con oca debe responder la pregunta. La estructura tiene un vector, para las respuestas.


Adjuntamos captura del código:
![Estructura Jugador](https://user-images.githubusercontent.com/101127695/170552772-3f13ecd0-ec91-4558-98d8-09d4c5622176.png)
![estructura](https://user-images.githubusercontent.com/101127695/170552778-f9f8b1ab-5fa8-4317-a347-831546af332a.jpeg)
