### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-infinity_its#5]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by IreneRico** [comment]
### FICHEROS 
En nuestro programa contamos con dos tipos de ficheros, aunque ambos son de lectura. 

1. **Ficheros de preguntas**:
Son ficheros de lectura, los cuales constan con 24 preguntas diferentes. Tenemos tres, cada uno con preguntas relacionadas con los diferentes temas que tenemos para elegir dentro de nuestro juego.
Captura de un ejemplo de preguntas: 
![Fichero de Preguntas](https://user-images.githubusercontent.com/100791927/170522210-9bde73fb-382a-400a-88a5-4230d94e097d.png)

2.**Ficheros de respuestas**: 
Son ficheros de lectura, los cuales tienen 24 respuestas a las preguntas de los otros  ficheros. Asimismo, tenemos tres ficheros, cada uno en función del tema que elija el jugador. 
Captura de un ejemplo de respuestas: 
![Fichero de Respuestas](https://user-images.githubusercontent.com/100791927/170522248-21fdb81e-3564-4b3b-8841-4455df9886ee.png)
