### ISSUE TITLE
Logo del proyecto

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-infinity_its#6]
Acompañando al código y a la documentación, debéis crear un logo que represente a vuestro proyecto. Este logo aparecerá en el [portfolio de proyectos de la web](https://aigora.github.io/#portfolio).
La imagen debe llamarse **logo.png** (respetando las minúsculas), debe estar en formato PNG, y sus dimensiones deben ser: 400 x 289 píxeles.
Esta imagen debe estar alojada en el nivel básico de vuestro repositorio (donde estén vuestros LICENSE y README.md).
Si lo necesitáis, tenéis una [web](https://imageresizer.com/) para modificar el tamaño o formato de vuestra imagen.
**Debéis cerrar esta issue cuando deis por entregado el logo.**

**Comment by Teresa-CorralesTorresano** [comment]
![logo png](https://user-images.githubusercontent.com/101127695/165805902-9daf3f14-2453-42f5-b91b-651bcf1ac2e5.jpg)

**Comment by Teresa-CorralesTorresano** [comment]
![logo](https://user-images.githubusercontent.com/101127695/170477969-732671fa-5534-4aa3-bcc4-2706bc2b8d7a.png)
